apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortly-deployment
  labels:
    app: shortly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortly
  template:
    metadata:
      labels:
        app: shortly
    spec:
      containers:
        - name: shortly
          image: venki1402/shortly:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
